### ISSUE TITLE
MacOS binary

### ISSUE THREAD

**Issue by aupilot** [pdet/Scrooge-McDuck#31]
Hi, 
It would be really great if you can add a Mac OS binary to the s3 bucket
Cheers,
Kir

**Comment by pdet** [comment]
Hi Kir,

I believe that the mac os binaries should be distributed for DuckDB 1.0. 
Can you share more about which DuckDB version you are using, which Mac processor, and a script where you have the commands used to install and load the extension?

**Comment by aupilot** [comment]
Hi Pedro,

I compiled the extension from the source code and I was able to install it via duckdb CLI. Now I can load the extension from python with con.load_extension("scrooge"). Although I'm not quite sure if it loads the version that came with duckdb or this is the one compiled from sources.

I'm using Macbook Pro with M2 cpu

Kir

**Comment by pdet** [comment]
I see,

If you are building the extension from the sources, the best way to ensure loading the correct extension is to the LOAD command with the path to the local extension lib.

e.g., 
```sql 
LOAD 'extension/scrooge/scrooge.duckdb_extension';
```

Be sure to activate the the extension unsigned flags when creating the connection. In python
```py 
con = duckdb.connect(':memory:', config={'allow_unsigned_extensions' : 'true'})
```

You might also need to avoid metadata-matching issues with:
```py
con.execute("SET allow_extensions_metadata_mismatch=true;")
```

**Comment by aupilot** [comment]
Thank you Pedro! BTW your extension is really awesome :)

**Comment by pdet** [comment]
> Thank you Pedro! BTW your extension is really awesome :)

Thanks for the kind words! Really appreciate it! ;-)
