### ISSUE TITLE
Support for DuckDB v1.1.0

### ISSUE THREAD

**Issue by carlopi** [pdet/Scrooge-McDuck#36]
Writing to notify that at this moment in time this extension do not successfully build or test against duckdb v1.1.0.

Extension will keep being available on duckdb v1.0.0, but can't be distributed on v1.1.0 until the problem is sorted out.

Problem, as detected by the test infrastructure is as follow: https://github.com/duckdb/community-extensions/actions/runs/10773618982/job/29873889918#step:16:5385
```
[3/10] (30%): /Users/runner/work/community-extensions/community-extensions/te...
Query unexpectedly succeeded! (/Users/runner/work/community-extensions/community-extensions/test/sql/scrooge/test_eth_scan.test:71)!
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
================================================================================
unittest is a Catch v2.13.7 host application.
Run with -? for options

-------------------------------------------------------------------------------
/Users/runner/work/community-extensions/community-extensions/test/sql/scrooge/
test_eth_scan.test
-------------------------------------------------------------------------------
/Users/runner/work/community-extensions/community-extensions/duckdb/test/sqlite/test_sqllogictest.cpp:219
...............................................................................

FROM read_eth(
    'USDT',
    'Transfer',
    99999999999,
    999999999999
);
```

More information / example of what other extension needed to change at https://github.com/duckdb/community-extensions/issues/85.

Thanks for being involved with the DuckDB community extensions!

**Comment by pdet** [comment]
Hi Carlo, thanks for all the hard work! I've updated scrooge and bumped in the community extensions repo!

I guess that should be it?

**Comment by carlopi** [comment]
Yep, https://github.com/duckdb/community-extensions/pull/110 looks good, test passed.
I will wait for CI to go through and then merge it.

I think this can then be closed, and thank you!
